// export const REMOVE_PIN = 'REMOVE_PIN';
export const ADD_PIN = 'ADD_PIN';
export const USER_UPLOAD_PIN = 'USER_UPLOAD_PIN';
export const USER_SELECTION_PHOTOS = 'USER_SELECTION_PHOTOS';
export const REMOVE_SAVED_PIN = 'REMOVE_SAVED_PIN'
export const REMOVE_USER_SELECTION_PHOTOS = 'REMOVE_USER_SELECTION_PHOTOS'